[project]
name = "apo-autogoal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.23"
dependencies = [
    "autogoal>=1.0.3",
    "datasets>=4.0.0",
]
